# Generated by Django 3.2.8 on 2021-10-23 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0002_comments_project_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_pic',
            new_name='profile_pic',
        ),
    ]
